### ISSUE TITLE
the app dose not work

### ISSUE THREAD

**Issue by PGogo** [mit-han-lab/litepose#10]
1. Crash occured once the app launched.
2. I notice that the output dimension of the tflite in the app is [1, 2]. But shouldn't the output be a heatmap?
Thanks for your great work. ^^

**Comment by meenchen** [comment]
1. The app has a dependency on Qualcomm SNPE to deploy our model on GPU. If the app crashes, it is likely the device does not support SNPE. 
2. Could you be more specific about the tflite model? The app should only use the `litepose494.dlc` that is compiled by SNPE. The file is in `lite_pose_mobile_demo.zip`.

**Comment by PGogo** [comment]
> 1. The app has a dependency on Qualcomm SNPE to deploy our model on GPU. If the app crashes, it is likely the device does not support SNPE.
> 2. Could you be more specific about the tflite model? The app should only use the `litepose494.dlc` that is compiled by SNPE. The file is in `lite_pose_mobile_demo.zip`.

I found it finally! I mistook "lite_pose_gpu_front_cam/assets/model_fp32.tflite" for the model. Thanks again!
