### ISSUE TITLE
How to test on custom images?

### ISSUE THREAD

**Issue by gsrujana** [mit-han-lab/litepose#16]
Hello, How to test on custom images or videos? Thanks

**Comment by MemorySlices** [comment]
Please refer to valid.py. It provides the pre/post-processing details which can be used to test on custom images/videos.

**Comment by gsrujana** [comment]
The details seem to be coming from cfg files. Seem like I need both images and annots to do inference. Can you point me to the code for inference on images without any labelled annots available? Thanks
