### ISSUE TITLE
nano_demo inference get error : ../nano_demo/checkpoints/lite_pose_nano/lib0.o: error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by YOOHYOJEONG** [mit-han-lab/litepose#35]
Hi.
I tried to run nano_demo/start.py in the order written on this link(https://github.com/mit-han-lab/litepose/tree/main/nano_demo).

But, I got this error:

Traceback (most recent call last):
  File "start.py", line 76, in <module>
    executor, gmod, device = get_model_executor()
  File "/workspace/litepose/nano_demo/core/__init__.py", line 94, in get_model_executor
    lib = tvm.runtime.load_module('/workspace/litepose/nano_demo/checkpoints/lite_pose_nano.tar')
  File "/anaconda3/envs/litepose/lib/python3.8/site-packages/tvm/runtime/module.py", line 610, in load_module
    _cc.create_shared(path + ".so", files)
  File "/anaconda3/envs/litepose/lib/python3.8/site-packages/tvm/contrib/cc.py", line 79, in create_shared
    _linux_compile(output, objects, options, cc, compile_shared=True)
  File "/anaconda3/envs/litepose/lib/python3.8/site-packages/tvm/contrib/cc.py", line 247, in _linux_compile
    raise RuntimeError(msg)
RuntimeError: Compilation error:
/usr/bin/ld:/workspace/litepose/nano_demo/checkpoints/lite_pose_nano/lib0.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld:/workspace/litepose/nano_demo/checkpoints/lite_pose_nano/lib0.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /workspace/litepose/nano_demo/checkpoints/lite_pose_nano/lib0.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /workspace/litepose/nano_demo/checkpoints/lite_pose_nano/lib0.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /workspace/litepose/nano_demo/checkpoints/lite_pose_nano/lib0.o: Relocations in generic ELF (EM: 183)
/workspace/litepose/nano_demo/checkpoints/lite_pose_nano/lib0.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status

Command line: /usr/bin/g++ -shared -fPIC -o /workspace/litepose/nano_demo/checkpoints/lite_pose_nano.tar.so /workspace/litepose/nano_demo/checkpoints/lite_pose_nano/lib0.o /workspace/litepose/nano_demo/checkpoints/lite_pose_nano/devc.o

When I run nano_demo/start.py, one folder(nano_demo/checkpoint/lite_pose_nano/) generated.
However, the files(devc.o, lib0.o) in the folder that were created seem to be causing errors.
What can I do?

(ps. I'm using a conda virtual environment. Does C++ have to be installed in my conda virtual environment?)

It may be a basic question, but I need help.

Help me...

Thank you!

**Comment by lmxyy** [comment]
Are you using Jetson nano?

**Comment by YOOHYOJEONG** [comment]
@lmxyy NO..  But, I Installed tvm on Window WSL.
Is this the problem?

**Comment by lmxyy** [comment]
Yes. TVM generates binary specific to a target platform.

**Comment by YOOHYOJEONG** [comment]
Okay... Thank you...
