### ISSUE TITLE
test Inference on video 

### ISSUE THREAD

**Issue by WizphysAi** [mit-han-lab/litepose#6]
Hey thank you for sharing your work, It looks really promising.
I want to test the model with webcam and custom video, which file should I use for inferencing ?

Thank you.

**Comment by lmxyy** [comment]
Hi, we have a complete end-to-end real-time video demo on Jetson Nano with TVM in [nano_demo](https://github.com/mit-han-lab/litepose/tree/main/nano_demo). You could refer to the webcam video stream preprocess and the post-process in the demo for your use. We will provide the webcam test code as soon as possible.

**Comment by mywordwin** [comment]
> We will provide the webcam test code as soon as possible.

Providing the webcam test code  is a good job，Very much looking forward to it.

Thank you.
